name: Push WordPress to ACR

on:
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ACR
        env:
          MY_USER: ${{ secrets.ACR_USERNAME }}
          MY_PASS: ${{ secrets.ACR_PASSWORD }}
        run: |
          echo "$MY_PASS" | docker login --username="$MY_USER" --password-stdin crpi-toh62d9r33b57uka.cn-beijing.personal.cr.aliyuncs.com

      - name: Pull and Push
        run: |
          # 1. 拉取你刚才报错的那个 WordPress 版本
          docker pull wordpress:6.7.2
          
          # 2. 打标签 (注意这里路径还是你的命名空间 my-test-repo1)
          docker tag wordpress:6.7.2 crpi-toh62d9r33b57uka.cn-beijing.personal.cr.aliyuncs.com/my-test-repo1/wordpress:6.7.2
          
          # 3. 推送到阿里云
          docker push crpi-toh62d9r33b57uka.cn-beijing.personal.cr.aliyuncs.com/my-test-repo1/wordpress:6.7.2
